from app.logger_classes.exception import CustomException


class LoginException(CustomException):
    pass
