from app.logger_classes.exception import CustomException


class RegisterException(CustomException):
    pass
